### ISSUE TITLE
NOT_FOUND happens

### ISSUE THREAD

**Issue by sshilko** [davidpersson/beanstalk#12]
Hi there, i'am actively using the library in production for more than a year, and while pushing the "limits" of how far i can go with it i now got an small issue.

the 

```
\Beanstalk\Client . _error
```

produces error log message "NOT_FOUND"

```
            [line] => 147
            [function] => error
            [class] => BackQ\Adapter\Beanstalk
            [type] => ->
            [args] => Array
                (
                    [0] => NOT_FOUND
                )

        )
```

I have my logger attached with simple error_log() wrapping.

Back to the issue. My call chain looks like:

```
$client = \Beanstalk\Client($config);
...
$client->connect();
...
$client->useTube('tubename1'); //result is 'USING'
$client->statsTube('tubename1); //result is 'NOT_FOUND'

// \Beanstalk\Client::statsTube
// \Beanstalk\Client::_statsRead
// \Beanstalk\Client::_error('NOT_FOUND')
```

I did read the Beanstalk [protocol spec](https://raw.githubusercontent.com/kr/beanstalkd/master/doc/protocol.txt) and i'am aware that:

```
Tubes are created on demand whenever they are referenced. If a tube is empty
(that is, it contains no ready, delayed, or buried jobs) and no client refers
to it, it will be deleted.
```

So i assume some worker took the last job from tube somewhere between "useTube" and "statsTube" and that causes the NOT_FOUND when the client is using tube that does not exists.
1. What exactly means "no client refers to it"
2. Is there a way to call stats on tube without triggering error (except ignoring the error itself) ?

Thx, greetings from Berlin

**Comment by mariuswilms** [comment]
Better late than never... sorry for the delay.

Yes, statsTube() may return false as a result, when the request returned something else than `OK`: https://github.com/davidpersson/beanstalk/blob/master/src/Client.php#L640

I agree: from reading the referenced spec section, it's not entirely clear when a tube exists. 

NOT_FOUND is a regular response and considered an error in other operations as well. I don't quite see what you think needs to be changed.

**Comment by sshilko** [comment]
thx anyway, i did own error handling around it.
