### ISSUE TITLE
Not recommended for production!

### ISSUE THREAD

**Issue by albus-optimus** [davidpersson/beanstalk#16]
Hello! Please make note "Not recommended for production!" for you library.

It is unstable, loses connection but does not understand this and continues to pretend that everything is ok. This leads to big problems!

**Comment by sshilko** [comment]
yes connection layer is not good, i replaced it

**Comment by mariuswilms** [comment]
I won't put up such a notice, because I don't agree with your statements. I'm using the library in production since 2009 without any connection issues. You should give more details so others can try to understand what the actual problem is.

**Comment by magnum-ferox** [comment]
when used in demon scripts, the library loses the connection to the broker and does not understand that it has lost it, stops reading and writing messages, does not throw exceptions, or does not report errors.

**Comment by sshilko** [comment]
The socket read/write handling does not handle that, @magnum-ferox you got to do your own, at least thats what i ended up doing, own socket read/write/connect/disconnect handling.

**Comment by sshilko** [comment]
@davidpersson  i can make a pull request with improved socket handling if you willing to review and merge it, i have your library running in production for >3 years and have most of socket handling issues covered bynow
