### ISSUE TITLE
function _write() issues

### ISSUE THREAD

**Issue by andygithubchen** [davidpersson/beanstalk#18]
Notice: fwrite(): send of 6 bytes failed with errno=32 Broken pipe  in ./Client.php on line 181

$data .= "\r\n";

change to :

$data .= '\r\n';

**Comment by andygithubchen** [comment]
Or not, this is better: @fwrite() , because just Notice . 🤪

**Comment by mariuswilms** [comment]
The proposed changes will not fix the error you are encountering. I assume the initial error happens because the connection has been closed.
